version: '3'

services:
#-----------------------------------------------------------------
  nginx1:
    image: nginx:latest
    volumes:
      - ./nginx1.conf:/etc/nginx/conf.d/nginx1.conf
      - ./laravel:/usr/share/nginx/html
    ports:
      - "8080:80"

  php1:
    build: .
    volumes:
      - ./laravel:/var/www/html
    depends_on:
      - mysql

#-----------------------------------------------------------------
  nginx2:
    image: nginx:latest
    volumes:
      - ./nginx2.conf:/etc/nginx/conf.d/nginx2.conf
      - ./laravel:/usr/share/nginx/html
    ports:
      - "8081:80"

  php2:
    build: .
    volumes:
      - ./laravel:/var/www/html
    depends_on:
      - mysql
#-----------------------------------------------------------------
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password