version: "3"
services:

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password


  nginx1:
    #build: ./nginx-dockerfile
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./laravel:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mysql
      - php1

  nginx2:
    #build: ./nginx-dockerfile
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./laravel:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mysql
      - php2

  php1:
    build: ./php-dockerfile
    volumes:
      - ./laravel:/var/www/html
    depends_on:
      - mysql
    links:
      - mysql
      
  php2:
    build: ./php-dockerfile
    volumes:
      - ./laravel:/var/www/html
    depends_on:
      - mysql
    links:
      - mysql


