version: "3"
services:

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password


  nginx1:
    #image: nginx:latest
    build: ./nginxDockerfile
    ports:
      - "8081:80"
    volumes:
      - ./laravel:/var/www/html
      - ./nginx1:/etc/nginx/conf.d
    environment:
      - SERVEUR_ID=Serveur_1
    depends_on:
      - mysql
      - php1

  nginx2:
    #image: nginx:latest
    build: ./nginxDockerfile
    ports:
      - "8082:80"
    volumes:
      - ./laravel:/var/www/html
      - ./nginx2:/etc/nginx/conf.d
    environment:
      - SERVEUR_ID=Serveur_2
    #command: chown -R www-data:www-data /var/www/html && chmod -R 775 /var/www/html
    depends_on:
      - mysql
      - php2


  php1:
    build: .
    volumes:
      - ./laravel:/var/www/html
    depends_on:
      - mysql

  php2:
    build: .
    volumes:
      - ./laravel:/var/www/html
    depends_on:
      - mysql
      - php1



